### ISSUE TITLE
Issues with setting this up

### ISSUE THREAD

**Issue by Moufeee** [zeobviouslyfakeacc/ModSettings#1]
Hello. I am pretty much oblivious to how to work with all this stuff, but I do my best. I am currently attempting to download the "Home Improvement" mod for TLD. I have setup WulfMarius's mod installer (0.6.3) and have sourced the said mod, and it shows in the library, but downloading the mod is locked under the reasons "requires missing dependencies: ModSettings^v1.4. I tried sourcing the ModSettings but it failed. I am unsure of how to overcome this. As I said, I am very limited in this field of play, and assistance would be appreciated. Sorry for my stupidity.

**Comment by zeobviouslyfakeacc** [comment]
Hmm, strange. Have you tried clicking the "refresh sources" button? Is there any kind of error message in the text box the Mod-Installer shows you?

**Comment by Moufeee** [comment]
Wow, you're fast. Refreshing didn't do the trick. The message displayed when the sourcing failed was as follows:
ADD: https://github.com/zeobviouslyfakeacc/ModSettings
	Loading definition
	Could not register source: me.wulfmarius.modinstaller.repository.SourceException: Could not read source description: 404, Not Found
FINISHED

**Comment by zeobviouslyfakeacc** [comment]
That's extremely strange. I'll let @WulfMarius know, maybe he knows what to do.

For now, you could first install the AssetLoader and ModComponent using the installer, and then just install ModSettings and HomeImprovement manually. To do the latter, first download `ModSettings.dll` from [here](https://github.com/zeobviouslyfakeacc/ModSettings/releases/tag/v1.4) and move it into your "mods" directory, and then download `Home-Improvement-V3.0.0.zip` from [here](https://github.com/WulfMarius/Home-Improvement/releases/tag/3.0.0) and extract the contents of that zip archive into the mods directory 😄

**Comment by Moufeee** [comment]
Gosh, that did it! Man, I love the Internet. And The Long Dark. Thanks for the help and all the work you put into modding this game!

**Comment by zeobviouslyfakeacc** [comment]
Awesome! Good to hear that at least the manual installation route still works 😄

**Comment by WulfMarius** [comment]
I'm just guessing here:

@Moufeee, you did not add the "Default Source" after installing the Mod-Installer, that's why you had to manually add the source for Home-Improvement.

Adding https://github.com/zeobviouslyfakeacc/ModSettings as source fails with a 404/Not found (and correctly so), because @zeobviouslyfakeacc has his descriptions in a different repository.

If this is all true, then the situation can be remedied by adding the default source manually.  
Use "Add Source" with the following URL: https://raw.githubusercontent.com/WulfMarius/Mod-Installer/master/descriptions/default-mod-installer-description.json

This will add a lot of mods and should not interfere with your manually adding Home-Improvement.  
The Mod-Installer will not detect that you manually installed any mods and still show them as "uninstalled", but it should be safe to just re-install them from the Mod-Installer.

HTH

**Comment by Moufeee** [comment]
@WulfMarius  Hey hey that did it! Also, I was wondering, and sorry if this is the wrong place to do this, but is there any chance of you to update/add to the Home Improvement mod itself? If so then downloading the mod through the ModInstaller would enable automatic updates, correct?

(Being able to remove dishes in houses would free up a lot of storage space, sorry if I'm being too irritating) 

Thanks a ton!
