### ISSUE TITLE
Something is wrong I think?

### ISSUE THREAD

**Issue by XKeith4** [zeobviouslyfakeacc/ModSettings#6]
Here is the log file. Do you need anything else? I am new to modding... Sorry.

[Latest.log](https://github.com/zeobviouslyfakeacc/ModSettings/files/8190931/Latest.log)

**Comment by zeobviouslyfakeacc** [comment]
Hi @XKeith4, sorry for taking so long to get back to you.

Judging from your log file, it doesn't look like ModSettings is to blame here, it's rather mods like FireImprovements and a few others. I'd encourage you to get support on the TLD modding discord server: https://discord.gg/VqCUgTJ

... but considering this issue is 20 days old by now, you probably already figured that out 😅
